### ISSUE TITLE
Error in function : Render

### ISSUE THREAD

**Issue by nartaki** [Stridemann/PoeHUD_FullRareSetManager#15]
Getting infinite amount of error counts rising when i open the stash...

**Comment by nartaki** [comment]
Log Entry : 16:20:14 Wednesday, 2 January, 2019
 Method error: Render : System.NullReferenceException: Object reference not set to an instance of an object.
   at PoeHUD.Poe.Elements.StashElement.GetStashName(Int32 index)
   at FullRareSetManager.Core.UpdateStashes() in C:\Users\Kristian\Documents\PoeHUD_FullRareSetManager\src\FullRareSetManager\Core.cs:line 675
   at FullRareSetManager.Core.Render() in C:\Users\Kristian\Documents\PoeHUD_FullRareSetManager\src\FullRareSetManager\Core.cs:line 105
   at PoeHUD.Plugins.BasePlugin._Render()
